extra/models.py
from sqlalchemy.ext.automap import automap_base
from flask_login import UserMixin

Base = automap_base()


class User(Base, UserMixin):
    __tablename__ = "users"

    def get_id(self):
        return self.user_id

extra/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import InputRequired, Length, EqualTo


class LoginForm(FlaskForm):
    recaptcha = RecaptchaField()
    username = StringField(validators=[InputRequired(), Length(min=4, max=30)],
                           render_kw={"placeholder": "Username"})
    password = PasswordField(validators=[InputRequired(), Length(min=4,
                                                                 max=30)],
                             render_kw={"placeholder": "Password"})
    submit = SubmitField("Login")


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField(validators=[InputRequired()],
                                 render_kw={"placeholder": "Old password"})
    new_password1 = PasswordField(validators=[
        InputRequired(),
        Length(min=4, max=30,
               message="Password must contain at least 4 characters")],
        render_kw={"placeholder": "New password"})
    new_password2 = PasswordField(validators=[
        InputRequired(),
        EqualTo("new_password1", message="New passwords must match")],
        render_kw={"placeholder": "Repeat new password"})
    submit = SubmitField("Change")

app.py
from flask import Flask, session
from flask_login import LoginManager
from extra.models import Base, User
from extra.extensions import db
from extra.database_accessories import connection_string_database
from blueprints.authentication import authentication
from blueprints.index import index
from datetime import timedelta
from credentials.application import secret_key
from credentials.recaptcha import recaptcha_public_key, recaptcha_private_key


def create_app():
    app = Flask(__name__)

    app.config["SQLALCHEMY_DATABASE_URI"] = f"mssql+pyodbc:///?odbc_connect={connection_string_database}"
    app.config["SECRET_KEY"] = secret_key
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True
    app.config["RECAPTCHA_PUBLIC_KEY"] = recaptcha_public_key
    app.config["RECAPTCHA_PRIVATE_KEY"] = recaptcha_private_key

    db.app = app
    db.init_app(app)

    Base.prepare(db.engine, reflect=True)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.session_protection = "strong"
    login_manager.login_view = "authentication.login"

    @login_manager.user_loader
    def load_user(user_id):
        return db.session.query(User).get(int(user_id))

    app.register_blueprint(authentication)
    app.register_blueprint(index)

    @app.before_first_request
    def make_session_permanent():
        session.permanent = True
        app.permanent_session_lifetime = timedelta(seconds=120)

    return app


app = create_app()
app.app_context().push()
app.run(host="0.0.0.0", port=80)

blueprints/authentication.py
from flask import Blueprint, render_template, redirect, url_for, flash
from extra.forms import LoginForm, ChangePasswordForm
from extra.models import User
from extra.extensions import db, flask_bcrypt
from flask_login import login_user, logout_user, login_required, current_user

authentication = Blueprint("authentication", __name__)


@authentication.route("/", methods=["GET", "POST"])
def login():
    form = LoginForm()

    user = db.session.query(User).filter_by(
        username=form.username.data).first()
    if form.validate_on_submit():
        if flask_bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for("index.main"))
        else:
            flash("Invalid username or password")
    return render_template("login.html", form=form)


@authentication.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("authentication.login"))


@authentication.route("/change_password", methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        condition1 = flask_bcrypt.check_password_hash(current_user.password,
                                                      form.old_password.data)
        if condition1:
            new_password_hash = flask_bcrypt.generate_password_hash(
                form.new_password1.data).decode("utf-8")
            db.session.query(User).filter_by(
                username=current_user.username).update(
                    dict(password=new_password_hash))
            db.session.commit()
            return redirect(url_for("index.main"))
        else:
            flash("Old password is incorrect")
    return render_template("change_password.html", form=form)

blueprints/index.py
from flask import (Blueprint, render_template, request, redirect, url_for,
                   session, flash)
from flask_login import login_required, current_user
from extra.database_accessories import (
    sql_query_w_fetch, sql_query_w_commit, create_sql_str_get_user_stats,
    create_sql_str_get_rows_for_unlabeled_images,
    create_sql_str_get_rows_for_labeled_images,
    create_sql_str_insert_label)
from credentials.blob_storage import sas_tocken
import numpy as np
import random


index = Blueprint("index", __name__)


@index.route("/main", methods=["GET", "POST"])
@login_required
def main():
    count_labels, count_labeled_images, count_not_labeled_images = \
        sql_query_w_fetch(
            create_sql_str_get_user_stats(current_user.username))[0]

    if count_not_labeled_images == 0:
        flash("There are currently no more images to label.")
        return redirect(url_for("authentication.logout"))

    # With 20% chance, an image that has already been labeld by the user
    # will be served for labeling again.
    serve_unlabeled_image = np.random.choice(
        np.array([True, False]), 1, p=[0.8, 0.2])[0]

    if (count_labels == 0) | serve_unlabeled_image:
        rows_images = sql_query_w_fetch(
            create_sql_str_get_rows_for_unlabeled_images(
                current_user.username))
        row_image = random.choice(rows_images)
        session["curent_image_id"] = row_image[0]
        url = row_image[1] + "?" + sas_tocken
    elif (~serve_unlabeled_image):
        rows_images = sql_query_w_fetch(
            create_sql_str_get_rows_for_labeled_images(
                current_user.username))
        row_image = random.choice(rows_images)
        session["curent_image_id"] = row_image[0]
        url = row_image[1] + "?" + sas_tocken
    return render_template("main.html",
                           url=url,
                           username=current_user.username,
                           count_labels=count_labels,
                           count_labeled_images=count_labeled_images,
                           count_not_labeled_images=count_not_labeled_images)


@index.route("/output", methods=["GET", "POST"])
@login_required
def output():
    label = request.form.get("label")
    image_id = session.get("curent_image_id", None)
    if label:
        try:
            sql_query_w_commit(create_sql_str_insert_label(
                current_user.username, image_id, label))
            return redirect(url_for("index.main"))
        except BaseException:
            return redirect(url_for("index.main"))
    else:
        return redirect(url_for("index.main"))

templates/change_password.html
<!doctype html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='mystyle1.css')}}">
</head>

<body>
    <main>
        <h1> Change Password </h1>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="action_field"> {{ form.old_password }} </div> </br>
            <div class="action_field"> {{ form.new_password1 }} </div> </br>
            <div class="action_field"> {{ form.new_password2 }} </div> </br>
            <div class="action_field"> {{ form.submit }} </div> </br>

            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                <li style="color:red;">{{ message }} </li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}

            <ul>
                {% for error in form.new_password1.errors %}
                <li style="color:red;"> {{ error }} </li>
                {% endfor %}
            </ul>
            <ul>
                {% for error in form.new_password2.errors %}
                <li style="color:red;"> {{ error }} </li>
                {% endfor %}
            </ul>

        </form>
    </main>
</body>

</html>

templates/login.html
<!doctype html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='mystyle1.css')}}">
</head>

<body>
    <main>
        <h1> Login </h1>
        <form method="POST" action="">
            {{ form.hidden_tag() }}

            <div class="action_field"> {{ form.recaptcha }} </div> </br>
            <div class="action_field"> {{ form.username }} </div> </br>
            <div class="action_field"> {{ form.password }} </div> </br>
            <div class="action_field"> {{ form.submit }} </div> </br>

            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                <li style="color:red;"> {{ message }} </li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}
        </form>
    </main>
</body>

</html>

templates/main.html
<!doctype html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='mystyle.css')}}">
</head>

<body>
    <div class="sidenav">
        <p>
            Statistic:
        <table line-height="0.8;">
            <tr>
                <td> User: </td>
                <td> {{username}} </td>
            </tr>
            <tr>
                <td> Submitted labels: </td>
                <td> {{count_labels}} </td>
            </tr>
            <tr>
                <td> Labeled images: </td>
                <td> {{count_labeled_images}} </td>
            </tr>
            <tr>
                <td> Images without label: </td>
                <td> {{count_not_labeled_images}} </td>
            </tr>
        </table>
        </p>

        <p>
            <a href="{{url_for('authentication.change_password')}}">
                Change password
            </a>
        </p>
        <p>
            <a href="{{url_for('authentication.logout')}}">
                Logout
            </a>
        </p>



    </div>
    <main>
        <h1> Label me! </h1>
        <p>
            This is a demo app. Please submit a label for the displayed
            image.
        </p>
        <p>
            Click on the image to zoom in.
        </p>

        <p>
        <div class="click-zoom" style="text-align: center;" id="layer1">
            <label>
                <input type="checkbox">
                <img src="{{url}}" height="400" width="400">
            </label>
        </div>
        </p>

        <form method="post" action="{{url_for('index.output')}}">
            <label for="label"> Label the image: </label>
            <select id="label" style="font-size:20px;" name="label">
                <option value="0"> 0 </option>
                <option value="1"> 1 </option>
                <option value="2"> 2 </option>
                <option value="3"> 3 </option>
                <option value="4"> 4 </option>
                <option value="5"> 5 </option>
                <option value="6"> 6 </option>
                <option value="7"> 7 </option>
                <option value="8"> 8 </option>
                <option value="9"> 9 </option>
            </select>
            <button type="submit" style="font-size:20px;"> Submit </button>
        </form>
    </main>
</body>

</html>